export const POST_REQUEST = 'POST_REQUEST';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';
export const LIST_MODIFY = 'LIST_MODIFY';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
